library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity LedDriver_tb is
end LedDriver_tb;

architecture Behavioral of LedDriver_tb is
    signal DataOut  : std_logic; 
    signal clk      : std_logic;
    signal AdresOut : STD_LOGIC_VECTOR (4 downto 0);
    signal DataIn   : STD_LOGIC_VECTOR (14 downto 0);
begin
     
DUT : entity work.LedDriver

port map (  DataOut => DataOut,
            clk => clk,
            AdresOut => AdresOut,
            DataIn  => DataIn
          );
   
the_stimuli: process
begin
    clk     <= '0';
    --AdresOut <= B"00000";
    Datain <= "100000000011111";
    --Datain <= B"111111111111111";
      
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    --Datain <= B"111111111111111";
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
        
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    wait for 10ns;
    clk <= not clk;
    
    
    wait;
    std.env.finish;
end process;

end Behavioral ; -- tb